# Generated by Django 3.1.7 on 2021-02-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Available_Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.format')),
            ],
        ),
    ]
