# Generated by Django 3.1.7 on 2021-02-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output_Format',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.RenameField(
            model_name='format',
            old_name='format',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='format',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='available_format',
            name='output',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.output_format'),
            preserve_default=False,
        ),
    ]
