# Generated by Django 3.1.7 on 2021-02-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210220_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Format',
            new_name='Input_Format',
        ),
    ]
