# Generated by Django 3.1.7 on 2021-02-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
