# Generated by Django 3.1.7 on 2021-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20210220_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='imagee',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
