# Generated by Django 3.1.7 on 2021-02-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_format_imagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.output_format'),
        ),
    ]
