# Generated by Django 3.1.7 on 2021-02-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_format_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='image',
        ),
        migrations.RemoveField(
            model_name='format',
            name='imagee',
        ),
    ]
