# Generated by Django 3.1.7 on 2021-02-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20210220_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='format',
            old_name='photo',
            new_name='available_format',
        ),
        migrations.RemoveField(
            model_name='available_format',
            name='output',
        ),
        migrations.AlterField(
            model_name='format',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.input_format'),
        ),
    ]
