# Generated by Django 3.1.7 on 2021-02-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20210220_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input_Format',
            new_name='All_Format',
        ),
        migrations.RemoveField(
            model_name='output_format',
            name='name',
        ),
        migrations.AddField(
            model_name='output_format',
            name='available_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.available_format'),
        ),
        migrations.AddField(
            model_name='output_format',
            name='output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.all_format'),
        ),
        migrations.AlterField(
            model_name='output_format',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Format',
        ),
    ]
