# Generated by Django 3.1.7 on 2021-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20210220_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_format',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
