# Generated by Django 3.1.7 on 2021-02-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20210220_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_format',
            name='name',
            field=models.CharField(default='hou', max_length=12),
            preserve_default=False,
        ),
    ]
