# Generated by Django 3.1.7 on 2021-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_input_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_file',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='input_file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='output_format',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
