# Generated by Django 3.1.7 on 2021-03-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20210311_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_format',
            name='name',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
