# Generated by Django 3.1.7 on 2021-03-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_auto_20210313_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='media/input'),
        ),
    ]
