# Generated by Django 3.1.7 on 2021-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_auto_20210313_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='output_document',
            field=models.FileField(blank=True, null=True, upload_to='media/output'),
        ),
    ]
