# Generated by Django 3.1.7 on 2021-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0027_auto_20210423_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=25)),
            ],
        ),
    ]
