# Generated by Django 3.1.7 on 2021-05-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0028_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_format',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
