# Generated by Django 3.1.7 on 2021-04-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat',
            field=models.JSONField(),
        ),
    ]
