# Generated by Django 3.1.7 on 2021-04-03 06:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0002_auto_20210402_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat',
            field=jsonfield.fields.JSONField(),
        ),
    ]
