# Generated by Django 3.1.7 on 2021-04-03 20:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0003_auto_20210403_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat',
            field=jsonfield.fields.JSONField(default=[['Welcome To', 'New Chat']]),
        ),
    ]
