# Generated by Django 3.1.7 on 2021-04-09 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chattingapp', '0005_auto_20210404_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
