# Generated by Django 3.1.7 on 2021-04-09 07:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chattingapp', '0007_auto_20210409_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection_room',
            name='chat',
            field=jsonfield.fields.JSONField(default=[['Welcome To', 'New Chat']]),
        ),
        migrations.AddField(
            model_name='connection_room',
            name='connection_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
